version: "3.3"
services:
  cie-backend:
    container_name: chaos-injection-engine-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./backend:/app
      - ~/chaosbank/deployment/v1:/v1
      - ~/chaosbank/deployment/v2:/v2
      - ~/.aws:/root/.aws
      - ~/aws-default.pem:/root/aws-default
    env_file: ./backend/.env
    ports:
      - "8080:8080"
    command: ["python3", "main.py"]
  mysql:
    image: mysql:8.0
    container_name: chaos-injection-engine-mysql
    restart: always
    env_file: ./backend/.env
    expose:
      - 3306
