version: "3.3"
services:
  cie-backend:
    container_name: chaos-injection-engine-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./backend:/app
      - ~/chaosbank/deployment/v1:/v1
      - ~/chaosbank/deployment/v2:/v2
      - ~/.aws:/root/.aws
    env_file: ./backend/.env
    ports:
      - "8080:8080"
    command: ["python3", "main.py"]
    networks:
      - cie-network
  mysql:
    image: mysql:8.0
    container_name: chaos-injection-engine-mysql
    restart: always
    env_file: ./backend/.env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cie-network
    # use expose if db and backend are in diff networks or hosts
    # ports:
    #   - "3306:3306"
    expose:
      - 3306

  prometheus:
    image: docker.io/prom/prometheus:v3.2.1
    container_name: prometheus
    ports:
      - 9090:9090
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus
    restart: unless-stopped

  grafana:
    image: docker.io/grafana/grafana-oss:11.6.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  mysql_data:

networks:
  cie-network:
    driver: bridge
